# Welcome to Jekyll!
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you: 
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: InterSystems製品を習得するためのラーニングパス
# email: your-email@example.com
description: >- # this means to ignore newlines until "baseurl:"
  このページでは、InterSystems 製品にご興味のある方、どんな製品であるか眺めてみたい方、これから開発予定の方向けに、製品の機能概要をご紹介するビデオ、参考となる記事、セルフラーニングビデオ、最適なコースを確認できるページです。
baseurl: "/LearningPathJP" # the subpath of your site, e.g. /blog
#url: "https://intersystems-community.github.io" # the base hostname & protocol for your site, e.g. http://example.com
# twitter_username: ""
# github_username:  ""

# Build settings
# theme: "just-the-docs"
remote_theme: pmarsceill/just-the-docs

# plugins:
  # - jekyll-feed

logo: "https://jp.community.intersystems.com/sites/all/themes/intersys/images/intersystems-logo.svg"

#color_scheme: isc

search_enabled: true
search:
  heading_level: 2
  previews: 3

aux_links:
  "GitHub Repo":
    "https://github.com/intersystems-community/vscode-objectscript"

#footer_content: "Copyright &copy; 2024 InterSystems Japan K.K. Distributed under an <a href=\"https://github.com/intersystems-community/vscode-objectscript/tree/master/LICENSE\">MIT license.</a>"

#ga_tracking: GTM-PKG7GB

  # Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/